### ISSUE TITLE
[Question and Feature request] TwoWireMD::set() cannot limit max power by myself

### ISSUE THREAD

**Issue by testusuke** [TaiyouKomazawa/InteractiveMD#8]
[https://github.com/TaiyouKomazawa/InteractiveMD/blob/bdd967bfbf5d38b3175d106c0123049a9da45663/Core/Src/TwoWireMD.cpp#L63](https://github.com/TaiyouKomazawa/InteractiveMD/blob/bdd967bfbf5d38b3175d106c0123049a9da45663/Core/Src/TwoWireMD.cpp#L63)
TwoWireMD cannot limit max PWM value by myself. It will be dangerous if MD does not have power limit. For instance, Yaju running by Hongo-Mechatech, that need to set PWM under 0.95(duty).
So, I request that implement **Power Limitter**.

**Comment by TaiyouKomazawa** [comment]
問題は #9 にて解決されるため閉じられます。
